apiVersion: v1
kind: Namespace

metadata:
  name: my-namespace

---

apiVersion: v1
kind: Pod

metadata:
  namespace: my-namespace
  name: multi-container-pod

spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep infinity"]

    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
