apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: setbased-pod

spec:
  replicas: 3

  selector:
    matchExpressions:
      - key: app
        operator: Exists

  template:
    metadata:
      name: pod
      labels:
        app: devops

    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
